---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This site is for further exploring results from my DSC comparing methods for covariance decomposition.  
  
Main takeaways thus far:  
  
* For flash with normal prior on F in the balanced, nonoverlapping setting, when I set Kmax to a large number, I find flash will add a bunch of factors whose loadings are a really small number. I'm still trying to figure out why it does that. Results [here](balanced_nonoverlapping_flash_normalf.html).  
* Flash's greedy method with gb priors does not do well in the tree setting. It always stops prematurely at 3 factors. Results [here](tree_ebmfcov_diag.html) and [here](tree_ebmfcov_greedy.html).  
* Flash with normal prior on F also struggles to find trees. When initialized with the true values, the method finds the factorization which clusters the samples by population. Perhaps it prefers that representation because it is more sparse? Results [here](tree_flash_normalf.html).  
* EBCD also struggles to find trees. However, when initialized with the true values, the method does yield an estimate that looks like a tree. So perhaps it is a convergence issue? My results are [here](tree_ebcd.html) and [here](tree_ebcd_part2.html).  

DSC analyses (9/8/2025):  
  
* [Results from the DSC](additive_clustering_comparison.html) (EB methods use generalized binary prior, the methods are given the correct number of components) and an [example of results](additive_clustering_comparison_pt2.html)    
* [Results comparing generalized binary prior and point-exponential prior](gb_vs_ptexp.html) and an [example of results using point exponential prior](gb_vs_ptexp_pt2.html)  
* [Results comparing different K inputs](input_K_comparison.html) and an [example of results using larger K](input_K_comparison_pt2.html)  
* [Results comparing methods from the same initialization](pt_laplace_split_init_comparison.html) and an [example of results](pt_laplace_split_init_comparison_pt2.html)

All other analyses:    
  
* Exploration of [similarity metrics and what thresholds to use](metric_threshold_exploration.html)  
* Exploration of [initialization in the balanced tree setting](init_comparison_baltree_setting.html)  
* Exploration of [initialization in the sparse overlapping setting](init_comparison_baltree_setting.html)  
* Comparison of [three different initializations](initialization_comparison.html)  
* Exploration of [EBMF with normal prior on F in Unbalanced, nonoverlapping setting](unbal_nonoverlap_pt_laplace_split_init_flash_normalf.html)
* Exploration of [EBMFcov with large K in the sparse, overlapping setting](sparse_overlapping_ebmfcov.html)  
* Exploration of [EBMFcov with different initializations in the sparse, overlapping setting](ebmfcov_init_comparison_sparse_overlapping.html)  
* Exploration of [GBCD in the Unbalanced tree setting](unbalanced_tree_analysis.html)  
* Exploration of [EBMFcov in Balanced, nonoverlapping setting](balanced_nonoverlapping_ebmfcov_diag.html)  
* Exploration of [EBMF with normal prior on F in Balanced, nonoverlapping setting](balanced_nonoverlapping_flash_normalf.html)  
* Exploration of [EBMF with normal prior on F in tree setting](tree_flash_normalf.html)  
* Exploration of [GBCD in tree setting](tree_gbcd.html)  
* Exploration of [EBMFcov in tree setting](tree_ebmfcov_diag.html)  
* Exploration of [Flashier's greedy method in tree setting](tree_ebmfcov_greedy.html)  
* Exploration of [symNMF in tree setting](tree_symnmf.html)  
* Exploration of [EBCD in tree setting](tree_ebcd.html)  
* Further exploration of [EBCD in tree setting](tree_ebcd_part2.html) 